engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      ignore_warnings: true
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**.php"
exclude_paths:
- "example.php"
- "helpers.php"
- "phpunit.php"
- "src/ThemeManager/config/**/*"
- "src/ThemeManager/ServiceProvider.php"
- "src/ThemeManager/Facade/**/*"
- "tests/**/*"
- "vendor/**/*"
